// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	chatApp "github.com/VSBrilyakov/chat-api"
	gomock "go.uber.org/mock/gomock"
)

// MockChatCommands is a mock of ChatCommands interface.
type MockChatCommands struct {
	ctrl     *gomock.Controller
	recorder *MockChatCommandsMockRecorder
	isgomock struct{}
}

// MockChatCommandsMockRecorder is the mock recorder for MockChatCommands.
type MockChatCommandsMockRecorder struct {
	mock *MockChatCommands
}

// NewMockChatCommands creates a new mock instance.
func NewMockChatCommands(ctrl *gomock.Controller) *MockChatCommands {
	mock := &MockChatCommands{ctrl: ctrl}
	mock.recorder = &MockChatCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatCommands) EXPECT() *MockChatCommandsMockRecorder {
	return m.recorder
}

// AddChat mocks base method.
func (m *MockChatCommands) AddChat(newChat *chatApp.Chat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChat", newChat)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChat indicates an expected call of AddChat.
func (mr *MockChatCommandsMockRecorder) AddChat(newChat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChat", reflect.TypeOf((*MockChatCommands)(nil).AddChat), newChat)
}

// AddMessage mocks base method.
func (m *MockChatCommands) AddMessage(newMsg *chatApp.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessage", newMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockChatCommandsMockRecorder) AddMessage(newMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockChatCommands)(nil).AddMessage), newMsg)
}

// DeleteChat mocks base method.
func (m *MockChatCommands) DeleteChat(chatId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatCommandsMockRecorder) DeleteChat(chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatCommands)(nil).DeleteChat), chatId)
}

// GetChat mocks base method.
func (m *MockChatCommands) GetChat(chatId, limit int) (*chatApp.ChatMessages, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", chatId, limit)
	ret0, _ := ret[0].(*chatApp.ChatMessages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatCommandsMockRecorder) GetChat(chatId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChatCommands)(nil).GetChat), chatId, limit)
}
